version: 0.2

env:
  variables:
    JEKYLL_ENV: "production"
   
phases:
  install:
    commands:
      - gem install bundler
  pre_build:
    commands:
      - bundle install
  build:
    commands:
      - bundle exec jekyll build
  post_build:
    commands:
      - aws s3 sync --delete --cache-control "max-age=300" --exclude assets/* _site/ "s3://tc.nz"
      - aws s3 sync --delete --cache-control "max-age=31536000" _site/assets "s3://tc.nz/assets"

artifacts:
  files: 
    - '**/*'
  base-directory: '_site*'
  discard-paths: yes